# Generated by Django 3.0.8 on 2020-08-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_auto_20200809_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskform',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
