# Generated by Django 3.0.8 on 2020-08-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_auto_20200809_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskform',
            name='created_on',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
